[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x565575"
blue = "0x65b2ff"
cyan = "0x63f2f1"
green = "0x62d196"
magenta = "0x906cff"
red = "0xff5458"
white = "0xa6b3cc"
yellow = "0xffb378"

[colors.normal]
black = "0x100e23"
blue = "0x91ddff"
cyan = "0xaaffe4"
green = "0x95ffa4"
magenta = "0xc991e1"
red = "0xff8080"
white = "0xcbe3e7"
yellow = "0xffe9aa"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"
mods = "Shift"

[scrolling]
history = 10000

[colors.primary]
background = "0x15181D"
foreground = "0xffffff"

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
resize_increments = false
startup_mode = "Windowed"
title = "Alacritty"
blur = true
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0 
